#!/usr/bin/env bash
#
# Copyright 2020 Chi-kwan Chan
# Copyright 2020 Steward Observatory
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

if test $# -ne 2; then
	echo "Usage: $0 [SRC_INTERNET] [DST_DOCKER]"
	exit 1
fi

set -e

src="$1"
dst="$2"

echo "Download \"$src\" from Internet to \"$dst\" in Docker image"

if ! which wget > /dev/null; then
	laniapt ca-certificates wget
fi

loc="/usr/local/src"
tmp="$loc/$(basename $src)"
wget  -q   "$src" -P "$loc"
mkdir -p   "$dst"
tar   -zxf "$tmp" -C "$dst" --strip-components=1
rm         "$tmp"
