#!/bin/bash -l
#
# Copyright 2019 Chi-kwan Chan
# Copyright 2019 Steward Observatory
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

# A hack to give the user a proper user name; see "selfadd.c"
export LOGNAME=$(/usr/local/sbin/selfadd -u)

export USER="$LOGNAME"
export HOME=$(eval echo ~$LOGNAME)

# Change directory to user home if it exists
if test -d "$HOME"; then
	cd "$HOME"
fi

# Run all commands
exec "$@"
